trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r ./confluence-pusher/requirements.txt
  displayName: 'Install dependencies'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      rm -f ./confluence-pusher/config.py;
      cp config_external.py ./confluence-pusher/config.py
  displayName: 'Replacing config.py with the version without Servian credentials'

- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: './setup.py'
    arguments: 'sdist'
  displayName: 'Building PyPi package'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      rm -f ./confluence-pusher/config.py;
      cp config_internal.py ./confluence-pusher/config.py
  displayName: 'Replacing config.py with the version with Servian credentials'

- task: TwineAuthenticate@1
  inputs:
    pythonUploadServiceConnection: 'PyPi_confluence_pusher_connection'
- script: 'twine upload -r "PyPi_confluence_pusher_connection" --config-file $(PYPIRC_PATH) dist/*'  
  displayName: 'Uploading package into PyPi repository'

